### ISSUE TITLE
[Request]: Reconsider 1+ for replies

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#101]
### Describe the request

I know that the Mastodon website does it too, but I don't think the 1+ thing for replies makes sense. Most other clients just show the actual count (as far as we know, I know there's potential for federation weirdness), so I'd follow that.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
I'm not opposed to showing the actual count for replies (and boosts + favs) though I understand the original position on why they are hidden: https://github.com/mastodon/mastodon/issues/420#issuecomment-270891339 (but at the same time, the official Mastodon app doesn't follow it anyway)
