### ISSUE TITLE
Toot/Post/Status & Profile bio content

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tooth#14]
Gtk labels cannot have images in them, making custom emoji support difficult.
At the same time we need to connect to signals that textview doesn't support (at least not as conveniently).

The current workaround I use for titles is to create a GtkButton with a box of GtkLabels and GtkImages from the title name (by splitting on `:`, checking for custom emojis etc).

While that kind-of works for titles, it doesn't for bios or toots because they require markup support.

My current plan is to use a webview to render them. Using a webview will also allow Tooth to support non-mastodon instances or future mastodon features like text formatting, markdown, latex, code blocks & more.

**Comment by chuangzhu** [comment]
How about using a non-editable text view? The `Text View > Multiple Views` in `gtk4-demo` has demonstrated having images in a TextView. And the `Text View > Markup` demo has showed how to make text view non-editable.

**Comment by GeopJr** [comment]
Thanks for your input!

We had a small discussion over this on #46 with 3 available options:

- textviews
- webviews
- [labels with widgets](https://gitlab.gnome.org/GNOME/fractal/-/blob/main/src/components/label_with_widgets.rs)

Textviews and Webviews will probably have a performance impact or other issues since each post will need at least 2.
Label with widgets is a custom widget from Fractal that, as the name implies, is a label with children (Fractal uses it for a similar reason as us, emojis in labels). Label with widgets is probably the ideal solution but it's a bit complex and nobody else seems to have ever rewritten it in vala so that's going to take a while.

**Comment by GeopJr** [comment]
Closing as duplicate of #1
