### ISSUE TITLE
Support RTL languages for single line texts

### ISSUE THREAD

**Issue by behDev** [GeopJr/Tooth#16]
#### What should happen:
Support RTL for single line texts

#### What happened instead:
If the RTL text is more than one line, it becomes RTL, but if it is single line, it becomes LTR

#### Screenshots:
- [ ] Something that is:

![Something that is](https://user-images.githubusercontent.com/82159958/204095544-b12e0055-db7c-4b10-881f-0782beb53398.png)

- [x] Something that should be:

![Something that should be](https://user-images.githubusercontent.com/82159958/204095613-1ecf5302-9819-4037-8b71-21381453d5d9.png)

#### Build context:
 - **Distro:** Debian Sid
 - **App version:** 2.1.0
 - **Build type:** Built from source

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Should be fixed as of f68be503d6a0b5cca975b87d6627f83ed6dc2b8e
