### ISSUE TITLE
incorrect toot text direction in RTL mode

### ISSUE THREAD

**Issue by behDev** [GeopJr/Tooth#19]
#### What happened:
incorrect toot text direction in RTL mode

#### Screenshots:

- [ ] RTL direction (incorrect):

![Screenshot from 2022-11-27 17-36-28](https://user-images.githubusercontent.com/82159958/204141879-77cf40c5-9e70-4447-ab93-1759b4b2a6c8.png)

- [x] LTR direction (correct):
![Screenshot from 2022-11-27 17-35-52](https://user-images.githubusercontent.com/82159958/204141888-12f40860-e5af-4f15-ac7b-dae2eb665967.png)

#### Build context:
 - **Distro:** Debian Sid
 - **App version:** 2.1.0
 - **Build type:** Built from source

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of aaabd3517aa04449b52d1ff2126e6100260bd957
