### ISSUE TITLE
Consider renaming?

### ISSUE THREAD

**Issue by Newbytee** [GeopJr/Tooth#28]
Hello! :wave: 

I think Tooth is inconsistent with the GNOME HIG section on naming recommendations given that I personally would not associate Mastodon with a tooth: https://developer.gnome.org/hig/guidelines/app-naming.html

Granted, I understand that these only are guidelines and don't need to be followed 100%, but I think having a name that is easy to associate with the application itself is nice. As such, I think it would be good to have a name associated with Mastodon. Maybe Trombone?

Feel free to disagree with me on this, but I wanted to propose it sooner than later given that renaming tends to go smoother the earlier you do it.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

I definitely agree that the name is *not ideal*.

The only reason **Toot**h was chosen is because it's close to **Toot**le. At the same time I don't really think Tooth, Tootle or Trombone associate with a Mastodon client. The **Toot** part of Tooth and Tootle no longer applies (Mastodon shifted away from it) and the sound part of Tootle and Trombone probably associates better with music or audio apps.

I've been particularly bad at naming apps (see Hashbrown => Collision, beardbin, exorcism) so I'm fully open to suggestions!

Other topics that could be used for inspiration:
- Mastodon (the animal)
- Fediverse
- Activitypub

**Comment by mozbugbox** [comment]
Mastooth or Mastodooth, Libretooth, Vastodon, Magui, Maclient...

An application name really should not be a simple English word. Hard to search over the internet.

**Comment by Newbytee** [comment]
> An application name really should not be a simple English word. Hard to search over the internet.

I suggest you read the GNOME HIG section I linked.

> Other topics that could be used for inspiration:

> - Mastodon (the animal)

I did a quick search for mastodon, the animal, and funnily enough the "don" part of it comes from the Ancient Greek word for word "tooth". However, while interesting, probably is a too far-fetched association.

How about Mammut, Missourium, or Leviathan?

**Comment by GeopJr** [comment]
Wish I had put that much thought into it but I literally just searched "words that start with toot" 😅 (A fitting alternative would be "Tusk" but there's already at least 2 Tusk themed apps (one of which being Tusky))

I like Mammut. My first thought on Missourium is that it will probably be a bit too hard to remember and for Leviathan that it's a bit too generic (mythology, books, movies etc).

Since Greek was brought up here's two other suggestions that roughly match the "gathering" and "socializing" parts of Mastodon: Symposium, Agora

Other than those, Cafe was another idea but it's also probably too generic or should be reserved for a coffee related app.

(This is still the brainstorming part of the process, if anyone reading this has any suggestions, feel free to comment them here)

**Comment by dilinger** [comment]
Fwiw, I actually think Tooth fits pretty well. "Mastodon" means "Nipple Tooth", and you've got "toot" in there as well. It will be difficult to google, though. Something like Toothy (similar to Tusky) might be easier to find.

I also don't see anything wrong with renaming back to Tootle and just continuing development under the old name, assuming Tootle's author isn't planning on doing anything further with the project and doesn't mind your fork. People already know Tootle, and it's already packaged in lots of distributions.

**Comment by FedericoCeratto** [comment]
FWIW a popular android client is named Fedilab, hinting at fediverse/federation rather than Mastodon. Perhaps in future there will be  popular ActivityPub server implementations compatible with the Mastodon client-to-server protocol (and therefore supported by Tooth).

**Comment by darltrash** [comment]
I second the name Mammut, it's really easy to remember and easy to associate with Mastodon in general.

**Comment by pravi** [comment]
Tootle is active again under gnome umbrella now https://gitlab.gnome.org/World/tootle I think it would be a good idea to join hands and contribute under gnome umbrella. What do you think?

**Comment by GeopJr** [comment]
Apart from being on World, there have only been 4 commits (unless I'm wrong). I can probably mirror Tooth to GNOME Gitlab if needed, but probably after a release.

**Comment by bleakgrey** [comment]
@pravi I was asked to migrate the repository to World in case anyone would be interested in maintaining it under its original name. It doesn't imply that I'm back at it, sorry if it brought any confusion.

**Comment by rsolvang** [comment]
One aspect to keep in mind regarding naming is the fact that new ActivityPub server projects keep popping up, most of which is more or less compatible with the Mastodon API. Finding a name that is not to closely tied to one specific implementation could be of importance for a GNOME project like Tooth, as it will be the go-to "portal" to the fediverse for many of these server implementations.

I'm personally running GoToSocial on my home server and, although it is still in an alpha state, it is largely compatible with the Mastodon API and I can use any client without trouble.

Keeping these facts in mind, I propose to direct the name search in a more general direction, towards what the fediverse is about: inter-connection, diversity, community and decentralization – to name a few core keywords.

**Comment by Pottit** [comment]
From the point of generalization, [Soapbox](https://en.wikipedia.org/wiki/Soapbox) could be a candidate; at it's core, it's a platform for speech. The connotations might be too political though, and the meaning might not be immediately clear to most people (like with most names, really). 

I guess this is also a question of the direction of the app - whether it should be developed as a Mastodon client or a client for ActivityPub more broadly.

**Comment by rsolvang** [comment]
@Pottit I kinda like your suggestion, it's a simple name and has connotations to speaking up about topics of interest ... but as you say, it might be too politically loaded. The fediverse is so much more and I feel the emphasis should be leaning more towards community and friendship. Twitter was closer to a soapbox, actually, and could often feel like shouting out into a dark void and maybe, just maybe some random people accidentally passing by would stop and listen, then shout back :) 

Hm, could "Friendly" work? It is a very general term, but it does communicate the intention of community. A lot of apps and website seems to use the -ly ending theses days, anyway. Or some other variation on this word? Tweaking it slightly to make it more unique certainly helps searchability.

**Comment by GeopJr** [comment]
"Soapbox" is already a fediverse frontend.

"Friendly" is a bit too generic as you mentioned. I feel like the two Greek words I mentioned earlier probably match what you are looking for:

> Since Greek was brought up here's two other suggestions that roughly match the "gathering" and "socializing" parts of Mastodon: Symposium, Agora

> https://github.com/GeopJr/Tooth/issues/28#issuecomment-1345436519

**Comment by FedericoCeratto** [comment]
If I might suggest names that remind of the federation and are unique... Fedifriend, Fedicafe', Federation Cafe', Fedipub? 

[I'm trying very hard not to suggest Ten Forward]

**Comment by j-mizzle** [comment]
> 

Are you able to log into GoToSocial with Tooth? Last time I tried I was unable to. I'll have to try again as that would make me very happy when my replacement Pinephone screen arrives.

**Comment by j-mizzle** [comment]
I

> One aspect to keep in mind regarding naming is the fact that new ActivityPub server projects keep popping up, most of which is more or less compatible with the Mastodon API. Finding a name that is not to closely tied to one specific implementation could be of importance for a GNOME project like Tooth, as it will be the go-to "portal" to the fediverse for many of these server implementations.
> 
> I'm personally running GoToSocial on my home server and, although it is still in an alpha state, it is largely compatible with the Mastodon API and I can use any client without trouble.
> 
> Keeping these facts in mind, I propose to direct the name search in a more general direction, towards what the fediverse is about: inter-connection, diversity, community and decentralization – to name a few core keywords.



> One aspect to keep in mind regarding naming is the fact that new ActivityPub server projects keep popping up, most of which is more or less compatible with the Mastodon API. Finding a name that is not to closely tied to one specific implementation could be of importance for a GNOME project like Tooth, as it will be the go-to "portal" to the fediverse for many of these server implementations.
> 
> I'm personally running GoToSocial on my home server and, although it is still in an alpha state, it is largely compatible with the Mastodon API and I can use any client without trouble.
> 
> Keeping these facts in mind, I propose to direct the name search in a more general direction, towards what the fediverse is about: inter-connection, diversity, community and decentralization – to name a few core keywords.

Are you able to log into GoToSocial with Tooth? Last time I tried I was unable to. I'll have to try again as that would make me very happy when my replacement Pinephone screen arrives.

**Comment by rsolvang** [comment]
> Are you able to log into GoToSocial with Tooth?

No, unfortunately not. I guess this will be resolved eventually as both GoToSocial and Tooth continues to develop and improve.

**Comment by TheEvilSkeleton** [comment]
I would recommend "Publish" (and desktop entry as "Publish for Mastodon", as it's over 15 characters), as it goes in line with the intended use case of Mastodon.

As for SEO, I don't think any of the names proposed are SEO friendly. However, we can always optimize the appstream file and allow certain keywords to be searchable in a front-end like GNOME Software.

**Comment by gregorni** [comment]
Isn't actually the correct English name for a Mammut "Mammoth"? I thought Mammut was German. But I'm all for one of those two.

**Comment by Newbytee** [comment]
> Isn't actually the correct English name for a Mammut "Mammoth"? I thought Mammut was German. But I'm all for one of those two.

The scientific classification of the genus is mammut. But otherwise you're right.

**Comment by GeopJr** [comment]
I made a form just to see what names are popular: https://forms.gle/zYpL9RHE8jjZDFjLA
(It's Google forms, no e-mail or account is required, the results are public)

**Comment by rsolvang** [comment]
This renaming has been churning in the back of my mind lately. What do you we to avoid to generic and SEO unfriendly names? Translate to latin :)

1. The latin word for Friendly: **Amicabilis**
    - Too long/complicated?
    - Found no app/brand that uses this name
2. The latin word for Speaking: **Loquens**
    - Easy to pronounce in most languages?
    - A scientific journal uses this name, but no brands
3. The latin translation of "having a chat": **Colloquens**
    - Same as above, but more emphasis on group communication 
    - Found no other app/brand using this name
4. The latin word for Interact: **Interagio**
    - Does have a nice ring to it
    - Seems to be used by a trading education website?
5. The swedish word for Discuss: **Talar**
    - Short and sweet, IKEA-ish :)
    - Found no app/company using this
6. The swedish/danish/german for for Interaction: **Interaktion**
    - This word is understood in most languages
    - Found no app/brand who uses it

All of these could be followed by "... for Mastodon", and a longer description could possibly expound with: "A client for fediverse servers compatible with the Mastodon API" or something to that affect.

**Comment by TheEvilSkeleton** [comment]
To be honest, all names you've mentioned are difficult for me to remember, except the last one. But Interaktion sounds more like a name that suits better for KDE.

**Comment by rsolvang** [comment]
@TheEvilSkeleton Yeah, reading them again a day after my brainstorm, I have to agree :smirk:

I do think the two last (non-latin) options is a step in the right direction, though, but I see your point about the k and association with KDE.

**Comment by rsolvang** [comment]
Ok, I'm not giving up! Some simpler, plain-word options :

1. Chatter
2. Banter
3. Converse
4. Frolic
5. Convey

**Comment by Newbytee** [comment]
Chatter sounds similar to Chatty: https://source.puri.sm/Librem5/chatty

**Comment by GeopJr** [comment]
Results are:
1. Mammut - 28
2. Publish - 23
3. Federation Cafe - 19

<details><summary>All</summary>

4. Friendly - 16
4. Toothy - 16
5. Tooth - 14
6. Trombone - 13
6. Symposium - 13
7. Agora - 12
8. Missourium - 8
8. Leviathan - 8

</details>

I like the top 3 and there's seems to be quite a big difference in votes between them and the others. I did take into consideration the last second submissions but they also fall under the following problem & last obstacle:

What kind of icon would the app have based on its name?
There's not really a "generic icon" for a microblogging app (chat bubbles are for chat apps for example) so it pretty much depends on its name.

- Mammut: That's an easy one, a Mastodon (animal) - con: majority of mastodon clients have a mastodon for their icon
- Publish: As much as I like this name, I can't think of a single icon that is not just a single arrow pointing up - which is already used by some apps
- Federation Cafe: A coffee cup

Any thoughts?

**Comment by TheEvilSkeleton** [comment]
> Publish: As much as I like this name, I can't think of a single icon that is not just a single arrow pointing up - which is already used by some apps

Perhaps you could ask in [#appicondesign:gnome.org](https://matrix.to/#/#appicondesign:gnome.org)? They might help you brainstorm and even design an icon.

**Comment by GeopJr** [comment]
> > Publish: As much as I like this name, I can't think of a single icon that is not just a single arrow pointing up - which is already used by some apps
> 
> Perhaps you could ask in [#appicondesign:gnome.org](https://matrix.to/#/#appicondesign:gnome.org)? They might help you brainstorm and even design an icon.

Thanks for the tip! Will definitely do, I just wanted to have the name ready + an icon idea as a start before asking but I guess "an arrow facing up" is enough. I'll have the final name decision ready tomorrow!

*(I'm trying to be a bit more prepared than the last time I had to deal with an app rename)*

**Comment by GeopJr** [comment]
Final decision: **Publish** for Mastodon

Thanks everyone for the submissions! Every single one of them was taken into account.

This is final, *unless we hit a roadblock with the icon designers*.

**Comment by bragefuglseth** [comment]
(The discussion was reopened after a discussion in the App Icon Design room)

According to GNOME’s naming guidelines, an app name should consist of one or two simple nouns.

Some suggestions based on this:

- Megaphone
- Interaction
- Lectern
- Dialog

«Megaphone» and «Lectern» would make for very easy icon metaphors.

**Comment by gregorni** [comment]
I'll look into the code and see if I can work on any of the other modes. I can't guarantee anything, though, because I don't know those Sinus and Cosinus functions.

**Comment by gregorni** [comment]
I think Dialog would be easily confused with [Dialect](https://github.com/dialect-app/dialect/).

A Megaphone icon could be made to look similar to the trumpet that's used right now. That's a plus in my book.

**Comment by snydox** [comment]
# I got a name: **Ivory**

**Comment by bragefuglseth** [comment]
[Already taken](https://tapbots.com/ivory/)

**Comment by a-wai** [comment]
I may lack some history there, but why not get back to "Mammut" as it was ranked 1st according to [this comment](https://github.com/GeopJr/Tooth/issues/28#issuecomment-1411016241)?

**Comment by bertob** [comment]
As discussed on Matrix, we realized a while back that Tuba would be a good name where it's feasible to make a nice icon. After a few iterations I think I have something that could work:

![image](https://user-images.githubusercontent.com/1908896/226974680-d17a8408-7713-4e0f-a0ff-d78bb3ed8056.png)

If this works for people I can open an MR :)

**Comment by jawsh207** [comment]
Instead of pitching this as a Mastodon client, why not pitch it as a "Fediverse" client. It already works with Pleroma/Akkoma and I believe it works with GoToSocial as well. Future updates could introduce features for other backends. You'll open up much more possibilities for naming. It'll also help educate people that it's not the "Mastodon Network". We need a "Fediverse Network" client.

**Comment by GeopJr** [comment]
That's already the goal! "Tuba" is generic enough, the summary is "Browse the Fediverse" and the description has [a section explaining the fediverse](https://github.com/GeopJr/Tooth/blob/bf0ee28/data/dev.geopjr.Tooth.appdata.xml.in)

**Comment by jawsh207** [comment]
> That's already the goal! "Tuba" is generic enough, the summary is "Browse the Fediverse" and the description has [a section explaining the fediverse](https://github.com/GeopJr/Tooth/blob/bf0ee28/data/dev.geopjr.Tooth.appdata.xml.in)

Oh, I guess my memory served me wrong here.
