### ISSUE TITLE
account view is truncated on mobile

### ISSUE THREAD

**Issue by primalmotion** [GeopJr/Tooth#30]
#### What should happen:
The view should fit the screen on mobiles

#### What happened instead:
The view is wider than the screen

#### How to reproduce:
Open any account view on mobile

#### Screenshots (if applicable):
![2022-12-12-142432](https://user-images.githubusercontent.com/208711/207168564-6f58e6ee-1e27-4a49-a74d-bb53d7faabeb.png)

#### Build context:
 - **Distro:**  PureOS Byzantium on Librem 5
 - **App version:** main
 - **Build type:** Built from source

#### Logs:
*(Terminal logs are often invaluable. If you can, launch the app from terminal with `dev.geopjr.tooth` and paste the output here)*

#### Additional info (if needed):
__

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of 7654dc36562833e32dbcded34f97c8f91382b435, if it still occurs please re-open this issue.

**Comment by primalmotion** [comment]
Fixed indeed! Thanks! And thanks for taking over tootle :)
