### ISSUE TITLE
unable to upload any image

### ISSUE THREAD

**Issue by primalmotion** [GeopJr/Tooth#31]
#### What should happen:
Sending images should work

#### What happened instead:
Well, it does not :)

#### How to reproduce:
Click the pencil icon
add some text
select the "media" tab
click "Add media" 
select an image
The path of the image is shown in the media tab
publish
Only the text is published, the media is nowhere to be found

#### Build context:
 - **Distro:** PureOS Byzantium
 - **App version:** main
 - **Build type:**  Built from source 

#### Logs:
There is no relevant log at all beside Gdk-WARNING: Compositor doesn't support moving popoups, relying on remapping

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Media uploading is now possible (as of #66)!

**Comment by primalmotion** [comment]
awesome thanks!

**Comment by primalmotion** [comment]
It's still not working for me :(

**Comment by primalmotion** [comment]
nah ignore me. I had two version of tooth installed for some reasons and my desktop file was launching the old one. it works :)

**Comment by f-engg** [comment]
I think this bug repeated itself somehow, in v0.9.1 on arch linux, was it just me?

**Comment by GeopJr** [comment]
This wasn't a bug, media uploading did not exist then and this issue was requesting it.

Please open a new issue with logs and I'll take a look! Media uploading should definitely work but I can help you figure out what the issue might be
