### ISSUE TITLE
Add ARM Flatpak to Github actions

### ISSUE THREAD

**Issue by mossymossmoss** [GeopJr/Tooth#41]
It would be nice to have Github actions produce an ARM Flatpak alongside the x86 one so that Tooth can be easily tested on mobile devices

**Comment by TheEvilSkeleton** [comment]
I can work on it, if this proposal gets accepted.

**Comment by GeopJr** [comment]
Go for it!

It's stalled because, since GitHub offers free aarch64 machines, I was trying to avoid using qemu [as suggested on the action readme](https://github.com/flatpak/flatpak-github-actions#building-for-multiple-cpu-architectures), but it would fail.

**Comment by TheEvilSkeleton** [comment]
What about setting up only for x86_64 for the time being?

**Comment by GeopJr** [comment]
Sure - the suggested workflow is just a bit wasteful by using both x86_64 & aarch64 machines AND qemu.

**Comment by TheEvilSkeleton** [comment]
Oh, looks like I don't need to? It's already in use: https://github.com/GeopJr/Tooth/blob/main/.github/workflows/build.yml

**Comment by GeopJr** [comment]
Oh I thought you meant setup qemu with the x86_64 one

**Comment by TheEvilSkeleton** [comment]
I just noticed that I completely overlooked "ARM" in the title... Jesus...

I'll work on ARM and see if you're okay with the amount of time it builds.
