### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by FedericoCeratto** [GeopJr/Tooth#49]
Hello and thanks for developing Tooth.
According to license_type in `src/Application.vala` and the badge in the `README.md` file Tooth is strictly under GPL v3.
According to `data/dev.geopjr.tooth.appdata.xml.in` it is under `GPL-3.0+` meaning that users can pick any future version of the license at they choice.

I understand that those files might come from @bleakgrey 's repo but this little conflict should be addressed anyways if possible.

(As a side note, it is considered a good practice to add a small comment at the top of each source code file to indicate authorship and license) 

Thank you!
Related to #27

**Comment by GeopJr** [comment]
I probably don't have a say on this but here's the blames:

Initial commit is "or later": https://github.com/bleakgrey/tootle/commit/30f8348286f4fe690b309409d7c438821710b8b2#diff-248a3ad2376574c96e7b8fc79764c5a217d4d41c8bf8679bcca1c3b7b87f8ff2R7

Granite drop is "only": https://github.com/bleakgrey/tootle/commit/748808d8457928c3548755e6d899380c5c2bd177#diff-94f3624867a327aa824c771318c113fe3a29c5149637a70aac408b786bf2ee35R15

(I'll consider license headers on each file!)

**Comment by FedericoCeratto** [comment]
Also this is the addition of the "only" in `src/Application.vala` https://github.com/bleakgrey/tootle/pull/310/files#diff-f4e5d48d751c670a8575715da1cb0a0976532427a8b6143c7fdede415a33ba6cR180

In my understanding regardless if @bleakgrey meant to use GPLv3 or GPLv3+ you are given the right to select GPLv3 [if that's what you want]

**Comment by GeopJr** [comment]
I went with `GPL-3.0`!

**Comment by Newbytee** [comment]
`GPL-3.0` and `GPL-3.0+` are deprecated identifiers according to SPDX: https://spdx.org/licenses/

`GPL-3.0-only` and `GPL-3.0-or-later` are preferred.

**Comment by GeopJr** [comment]
Done! (Changed to `GPL-3.0-only`)
