### ISSUE TITLE
Remove or fix unmaintained features

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tooth#5]
Many features got semi-disabled (or were left broken) after the gtk4 PR.

- Account switcher
~~Removing accounts doesn't seem to work.~~ fixed
Streams and notifications get mixed.

- Content Warnings
~~The code still exists (and still causes issues https://github.com/GeopJr/Tooth/commit/269549fdeeff0ea2f9e12184d3fe643d04fec6bd) but seems to be semi-disabled.~~ added

- ~~Lists~~ fixed

Additionally, some parts are way too over-engineered for no clear reason (or I am just too unfamiliar with Vala).

Lastly, after this is done, all commented out code should also be removed.

**Comment by rffontenelle** [comment]
Maybe display a warning saying that it is currently not implemented? I came across with Lists not adding and found this issue.

**Comment by GeopJr** [comment]
Considering there's no tagged release yet I don't think a warning is needed (plus it might attract potential PRs to fix it).

**Comment by GeopJr** [comment]
Lists should now be fully working! #36
