### ISSUE TITLE
[Request]: GoToSocial support

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tooth#51]
### Describe the request

Support GoToSocial

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
GoToSocial should now work as expected @j-mizzle @rsolvang!

(GoToSocial would return 418 ([I'm a teapot](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418)) if user-agent was blank)

**Comment by rsolvang** [comment]
I works! Thanks so much, @Geopjr!
