### ISSUE TITLE
[Request]: Update name with one that complies with the GNOME HIG

### ISSUE THREAD

**Issue by TheEvilSkeleton** [GeopJr/Tooth#56]
### Describe the request

I propose to change the name of Tooth to one that complies with the GNOME HIG. The [GNOME App Naming guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html) discourages the use of puns. I'm not sure, but "Tooth" is a pun right?

What do you think? We can brainstorm if this proposal is accepted.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by TheEvilSkeleton** [comment]
Admiditly, I searched for an existing issue *after*. I opened this one. My apologies https://github.com/GeopJr/Tooth/issues/28.

**Comment by GeopJr** [comment]
(If you have any last minute proposals, feel free to comment them there!)
