### ISSUE TITLE
Select text, copy

### ISSUE THREAD

**Issue by eisfuchs-de** [GeopJr/Tooth#60]
Standard text selection to copy text would be very handy. Right now, clicking a toot will open the full text, but even there I can't select or copy text. Please consider enabling this feature. Thank you for your work on a native Linux Mastodon client!

**Comment by eisfuchs-de** [comment]
Seems like I can just set "selectable" to "true" in src/Widgets/MarkupView.vala - To open a toot I then have to click on the time/globe icon in the top right, which works for me. What do you think?

**Comment by GeopJr** [comment]
Thanks for the suggestion, it should be done as of 403487a35d91a24d709427504f935ab5fbfcb786!

**Comment by eisfuchs-de** [comment]
Oh, very nice, thank you!
