### ISSUE TITLE
[Bug]: Wrap tooltip text

### ISSUE THREAD

**Issue by kdwk** [GeopJr/Tooth#64]
### Describe the bug

Tooltips with long text can extend the length of the monitor, which is not ideal. Tooltips should have a maximum size and their text should be wrapped.

### Steps To Reproduce

1. Open a post that contains an image with long alt text
2. Hover over the image
3. Observe the tooltip

### Logs and/or Screenshots

![Screenshot from 2023-01-25 14-30-27](https://user-images.githubusercontent.com/39268094/214496729-a1cc6518-6bc3-44a5-b49c-0f85d0010f30.png)

### Instance Backend

Mastodon

### Operating System

Fedora Silverblue 37

### Package

Flatpak

### Troubleshooting information

flatpak: true
version: main-4e53d0e (development)
gtk: 4.8.3 (4.8.3)
libadwaita: 1.2.1 (1.2.1)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Using the tooltip as alt text wasn't that practical to begin with: You can't select it and it can be much bigger than what can fit on a tooltip.

So instead I added a dedicated button & set the Gtk.Picture alternative_text property to it for screen readers:

![Screenshot of an image attachment on a post on the Tooth GTK app. The attachment badge shows 2 linked widgets: 1 label with the text IMAGE and one button with the text ALT](https://user-images.githubusercontent.com/18014039/214529904-64bb0d66-0231-4b29-b150-708da41cd366.png)

![Screenshot of a modal window on the Tooth GTK app. Its title is Alternative text for IMAGE and its content is a label with the previous image's alt text](https://user-images.githubusercontent.com/18014039/214530124-fc619111-f44a-4558-b1e3-aaf15dcbf265.png)

Let me know if that fixed or not your issue!
