### ISSUE TITLE
[Bug]: Text overflows its content area in some languages

### ISSUE THREAD

**Issue by garrett** [GeopJr/Tooth#67]
### Describe the bug

Text overflows the content area. This looks like it's due to using Japanese mixed in with other languages.

### Steps To Reproduce

The message is @ https://toot.community/@LostCabinPress/109773469157032332 and is in Japanese mixed with English, German, Spanish, and Italian.

### Logs and/or Screenshots

![image](https://user-images.githubusercontent.com/10246/215341242-cd32042c-7f42-407c-a61c-9024d3fb5ad0.png)

### Instance Backend

Mastodon

### Operating System

Fedora

### Package

Flatpak

### Troubleshooting information

I compiled this manually but am running it via Flatpak on Fedora 37 Silverblue.

**Comment by garrett** [comment]
Oddly, when I toggled larger text on, it works as expected!

![image](https://user-images.githubusercontent.com/10246/215342105-368914f4-4968-43b9-9da8-ae88fe8cc720.png)

(The other message is for context, to show how typical messages look, by-the-way.)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It *should* be fixed but I'm unsure if setting the markup view to horizontal broke anything else, so let me know if you encounter anything!

I also noticed from your screenshots that the attachment badge text color was black on light mode - fixed!
