### ISSUE TITLE
[Bug]: Can I install stable version?

### ISSUE THREAD

**Issue by ChibyX** [GeopJr/Tooth#72]
### Describe the bug

Hello. I installed this app from source on Fedora 37, and it has icon and toolbar like it's beta (or smth like that). Is there a way to install version without it or remove these decorative issues?

(Sorry if this is a wrong place to ask or it's a dumb question)

### Steps To Reproduce

Just open app

### Logs and/or Screenshots

```
<paste your logs here>
```
![изображение](https://user-images.githubusercontent.com/118626347/219032908-c8a702a4-9eff-4083-924a-9167eee9dc10.png)
![изображение](https://user-images.githubusercontent.com/118626347/219032978-2c674687-b6ef-4e77-b9b2-feaf250fe801.png)

### Instance Backend

Mastodon

### Operating System

Fedora 37

### Package

Compiled manually

### Troubleshooting information

flatpak: false
version: main-282f303 (development)
gtk: 4.8.3 (4.8.3)
libadwaita: 1.2.0 (1.2.0)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
There's no "stable" release yet, hence the decorations, but you can remove them by editing the install script so devel is false:

```diff
-- meson configure build -Ddevel=true
++ meson configure build -Ddevel=false
```
