### ISSUE TITLE
[Bug]: Favorite yellow is too light

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#80]
### Describe the bug

The yellow used for the favorite star is much lighter than the other colors, and too low-contrast. I'd try a darker yellow, e.g. #e5a50a (darkest yellow on the GNOME palette), or if that's still too light a sightly darkened version of that.

### Steps To Reproduce

1. Open the app
2. Star a post

### Logs and/or Screenshots

![image](https://user-images.githubusercontent.com/1908896/225271673-7a45fb2b-2172-4ba8-9a2e-7590a1d1adae.png)

### Instance Backend

Mastodon

### Operating System

Fedora 37

### Package

Flatpak

### Troubleshooting information

os: GNOME 43 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-c31521b (development)
gtk: 4.8.3 (4.8.3)
libadwaita: 1.2.2 (1.2.2)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Here's how they look; we could also use orange in light mode:

Yellow 4:

![image](https://user-images.githubusercontent.com/18014039/225275279-3b88ccaf-49f2-4f0b-a45b-8ef840fa6e91.png)

Yellow 5:

![image](https://user-images.githubusercontent.com/18014039/225275423-6ab57266-f792-4155-8c58-428a95e332f0.png)

Darker Yellow 2:

![image](https://user-images.githubusercontent.com/18014039/225275648-571c2c6b-9141-4785-98ff-3b3f2e35740f.png)

Orange 2:

![image](https://user-images.githubusercontent.com/18014039/225275982-41abf061-306b-4f36-8d02-39306801dff9.png)

Orange 3:

![image](https://user-images.githubusercontent.com/18014039/225276046-90bebca4-ecad-48ec-b096-765a175247d8.png)

**Comment by bertob** [comment]
Yellow 5 looks good to me, I think!
