### ISSUE TITLE
[Request]: Improve boost styling

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#81]
### Describe the request

The large button with the visible background for boosts makes them stand out a bit too much in the timeline.

![image](https://user-images.githubusercontent.com/1908896/225296749-fab7728c-7eec-4cc3-876c-68b9dad9c620.png)

I'd try something like this:
- Smaller text size
- Dimmed style
- Less padding
- .flat background

On top of that it could be interesting to do something similar to Elk, with a smaller booser avatar behind the author avatar, like so:

![image](https://user-images.githubusercontent.com/1908896/225295975-b60be91c-fe91-4db8-bfe9-e4d4bbdf77fd.png)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/18014039/225317663-7dbf7143-609d-48e4-8e81-083069074080.png)

we have a lot of space at the top left so I thought I might as well put it there

**Comment by GeopJr** [comment]
behind the author's avatar:

![image](https://user-images.githubusercontent.com/18014039/225469286-505146bc-62ce-4841-84dc-65eabc6eb4aa.png)

**Comment by bertob** [comment]
The last one with no bottom margin looks great to me, no strong opinion about the color.

**Comment by GeopJr** [comment]
I went without colors for now!
