### ISSUE TITLE
[Request]: Improve padding on posts

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#84]
### Describe the request

The padding on posts is a bit too narrow, I'd increase it to e.g. 18px.

![image](https://user-images.githubusercontent.com/1908896/225918591-51186e05-6df6-4040-b449-269e1ab86350.png)

Inspector hack with 18:

![image](https://user-images.githubusercontent.com/1908896/225918118-760f8103-c24b-4a61-8219-a6c6a7c78ed0.png)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Which one looks better?

12px:

![image](https://user-images.githubusercontent.com/18014039/225958317-8ef4392f-8da4-4770-9e0e-08666814f95c.png)

16px:

![image](https://user-images.githubusercontent.com/18014039/225958494-6e61a193-841f-486f-8a68-a2106148b07c.png)

18px:

![image](https://user-images.githubusercontent.com/18014039/225958601-87ac7345-6f24-4530-b46e-bab265131a98.png)

**Comment by bertob** [comment]
12 works for me, I guess that's in addition to the spacing that was already there so it works out to like 18 overall.
