### ISSUE TITLE
[Request]: Move Follow button to view

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#89]
### Describe the request

The Follow/Unfollow button is currently in the headerbar, which looks awkward on narrow sizes, especially because there's more space below next to the name.

![image](https://user-images.githubusercontent.com/1908896/225981130-0c1c29e4-b150-405a-9217-046e4bf04e87.png)

Here's what other clients do:

Elk:

![image](https://user-images.githubusercontent.com/1908896/225982002-63116cc4-d053-44f6-b85c-b81b290826cf.png)

Mastodon website:

![image](https://user-images.githubusercontent.com/1908896/225982258-f5bc0d17-afdf-497e-8851-01159d9f135a.png)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
How does this look?

Not sure if the relationship status badge and the follow button being too close is too cluttered

![image](https://user-images.githubusercontent.com/18014039/226078203-657df55b-dcc4-49d3-95f8-4d1a8774fb65.png)

![image](https://user-images.githubusercontent.com/18014039/226078224-089296fb-3fd1-4205-aef6-afba100bc27c.png)

it can be moved if needed:

![image](https://user-images.githubusercontent.com/18014039/226078373-a7793870-376c-4d25-a017-44e3604eb27d.png)

**Comment by bertob** [comment]
I like the top right one from those screenshots, I'd go with that for now, see how it works out, and potentially iterate.
