### ISSUE TITLE
[Request]: Improve button alignment on posts

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#90]
### Describe the request

Currently the buttons below a post have padding on the left and right, so the first and last ones are not aligned with the text column above:

![image](https://user-images.githubusercontent.com/1908896/225985030-897d9261-e007-4a23-9dbe-8e9a2d69113c.png)

In Elk (and most other clients) the buttons don't have that extra padding, so the layout looks more harmonious:

![image](https://user-images.githubusercontent.com/1908896/225985200-6e25fb3f-7ba4-4f64-89e5-b17ebedab92e.png)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/18014039/226080570-6f65a54c-5553-420c-9e0a-690040c6ee12.png)

![image](https://user-images.githubusercontent.com/18014039/226080594-b06b3d31-319e-4dac-be34-2f4d165808f8.png)

**Comment by bertob** [comment]
Looks great, ship it :ok_hand:
