### ISSUE TITLE
[Request]: Media thumbnail overlay papercuts

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#94]
### Describe the request

Currently media thumbnails have overlays showing the media types, and a second overlay for the alt text. This is very heavy visually and clutters up the previews too much IMO.

![image](https://user-images.githubusercontent.com/1908896/226142238-d8f5f88c-1681-4559-97d6-550e0c3fe987.png)

![image](https://user-images.githubusercontent.com/1908896/226142754-0a8d9ac7-893a-444d-932d-97bf7e9ffd9c.png)

![image](https://user-images.githubusercontent.com/1908896/226142352-f0143516-fbd6-4f85-a45f-56f871d86ab1.png)

For comparison, Elk doesn't have the image/video label and the ALT label is smaller and has less padding. I'd suggest doing something similar for images, and for videos I'd either have an overlay play button in the center, or maybe have an actual mini-player in the timeline, like Elk does.

![image](https://user-images.githubusercontent.com/1908896/226142884-5cc57816-64bf-4f65-9e32-6e9a0470bed5.png)

![image](https://user-images.githubusercontent.com/1908896/226143119-054ad1a6-7a6b-438e-86bc-9af162041b36.png)

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
How does this look so far?

I haven't changed the "ALT" font size, just the padding:

![image](https://user-images.githubusercontent.com/18014039/226158579-a8014dd5-fb84-4c57-aea2-64a93e7f6966.png)

I'm not sure what's the best way to handle a mini-player - while Mastodon allows 1 video per post, Pleroma (& others) don't have a limit. Maybe only show one if there's 1 video attachment? Probably for another issue though

Btw, elk seems to have a cover fit for attachments which we can also do if I move forward with #52 

contain:
![image](https://user-images.githubusercontent.com/18014039/226159031-7772305c-e406-439e-bb91-6e497e93a8db.png)

cover:
![image](https://user-images.githubusercontent.com/18014039/226159071-dd36718f-b949-433d-ac7b-2b808c6b7c83.png)

**Comment by bertob** [comment]
> How does this look so far?

I'd maybe add an .osd circle behind the play icon, instead of darkening the whole video, but looks good otherwise.

> Btw, elk seems to have a cover fit for attachments which we can also do if I move forward with https://github.com/GeopJr/Tooth/pull/52

Yeah, that'd be nice :+1:
