### ISSUE TITLE
[Bug]: Command line option --hidden non-functional

### ISSUE THREAD

**Issue by gregthwuen** [GeopJr/Tooth#98]
### Describe the bug

As stated in the command line help, Tooth provides a command line option to be started in the background:

```
Application Options:
  --hidden         Do not show main window on start
```

This option appears to be non-functional, since the app always starts in the foreground, both with and without the flag. No errors are shown in the log with the option provided.

### Steps To Reproduce

1. Start tooth with the `--hidden` flag.
2. Tooth starts in the foreground with no errors shown.

### Instance Backend

Mastodon

### Operating System

Arch Linux (rolling)

### Package

Compiled manually

### Troubleshooting information

os: Arch Linux (null)
prefix: /usr
flatpak: false
version: 0.1.0 (production)
gtk: 4.10.1 (4.10.1)
libadwaita: 1.2.3 (1.2.3)
libsoup: 2.74.3 (2.74.3)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of a46a7e19f1a9ff3a1b8ecb7edb9d6bc38527cec8
