### ISSUE TITLE
[Request]: Be more aggressive in loading timeline

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tooth#99]
### Describe the request

It's currently pretty easy to get to the last post and have to wait for more posts to load. It'd be better to pre-load the next posts sooner, so you never reach the last post at normal scrolling speeds. I think Fractal does something like this for the timeline.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by bertob** [comment]
What does "posts per page" mean? I saw that setting and didn't understand it, since there's no pagination, just scrolling. Is a page just the number of posts being loaded together when more posts are loaded?

**Comment by GeopJr** [comment]
yeah, "posts per load batch" might be a slightly better name:

12:

![image](https://user-images.githubusercontent.com/18014039/226427339-cf96d69f-8f23-400c-a7b6-ed995f9fb4c5.png)

40:

![image](https://user-images.githubusercontent.com/18014039/226427431-d86fd064-bf8e-4dc1-a195-caabb9d1787e.png)

**Comment by bertob** [comment]
Indeed, +1 for renaming that in the UI. And yes, maybe increasing it to 20 or so could be good.

**Comment by stacyharper** [comment]
I still encounter a lot of freeze while reaching the bottom of the posts. On mobile devices, this is specifically annoying cause loading next posts can take quite a long time.

I'll try to increase the batch value, but is there other planned solution to solve this?

**Comment by GeopJr** [comment]
Moved it to #410

Increasing the batch size *might* increase the freezing instead (since more post widgets need to be generated at the same time)
